### ISSUE TITLE
async-task bug

### ISSUE THREAD

**Issue by he426100** [friendsofhyperf/components#249]
日志
```log
[2023-06-19 16:04:31] task.INFO: [2023-06-19 16:04:31] Processing App\Task\BlockNotifyTask. [] []
[2023-06-19 16:04:31] http.INFO: skeleton 8.129.98.15 [19/Jun/2023:16:04:31 +0800] "POST /api/block/getBlockTransactionInfo HTTP/1.1" 200 50 "" "GuzzleHttp/7" "" 0.001 - -
 [] []
[2023-06-19 16:04:31] task.ERROR: [2023-06-19 16:04:31] Failed App\Task\BlockNotifyTask. [] []
[2023-06-19 16:04:31] task.ERROR: ArgumentCountError: Too few arguments to function FriendsOfHyperf\AsyncTask\Task::FriendsOfHyperf\AsyncTask\{closure}(), 1 passed in /opt/www/vendor/friendsofhyperf/support/src/Functions.php on line 45 and exactly 2 expected in /opt/www/vendor/friendsofhyperf/async-task/src/Task.php:92
Stack trace:
#0 /opt/www/vendor/friendsofhyperf/support/src/Functions.php(45): FriendsOfHyperf\AsyncTask\Task::FriendsOfHyperf\AsyncTask\{closure}()
#1 /opt/www/vendor/friendsofhyperf/async-task/src/Task.php(95): FriendsOfHyperf\Support\retry()
#2 /opt/www/vendor/friendsofhyperf/async-task/src/Listener/OnPipeMessageListener.php(43): FriendsOfHyperf\AsyncTask\Task::execute()
#3 /opt/www/vendor/hyperf/event/src/EventDispatcher.php(36): FriendsOfHyperf\AsyncTask\Listener\OnPipeMessageListener->process()
#4 /opt/www/vendor/hyperf/framework/src/Bootstrap/PipeMessageCallback.php(30): Hyperf\Event\EventDispatcher->dispatch()
#5 [internal function]: Hyperf\Framework\Bootstrap\PipeMessageCallback->onPipeMessage()
```

调用代码
```
use App\Task\BlockNotifyTask;
use FriendsOfHyperf\AsyncTask\Task;

Task::deliver(new BlockNotifyTask(compact('height', 'notifyUrl')));
```

尝试解决报错
```
# support/Functions.php:45
$callback($attempts, null);
```

**Comment by huangdijia** [comment]
```shell
composer require friendsofhyperf/async-task:3.0.x-dev
```

试试看，正常没问题我就打 tag
